### ISSUE TITLE
Can't open the release app bundle

### ISSUE THREAD

**Issue by LeonidKokhnovich** [seanhenry/SwiftMockGeneratorForXcode#1]
When I copied the app to Applications folder and try to open it, it gives an error:

“MockGeneratorApp.app” is damaged and can’t be opened. You should move it to the Trash.

I have Mac OS X 10.12.6

**Comment by LeonidKokhnovich** [comment]
Here is what I see in the system console:

16:15:43.722875 -0700	CoreServicesUIAgent	com.apple.message.domain: com.apple.usage.gatekeeper.open-unsafe-executable-type
com.apple.message.signature: com.apple.application-bundle
com.apple.message.signature2: LSRiskCategoryUnsafeExecutable
SenderMachUUID: 5041F021-9F74-3CE5-8E96-58DBFE1822AF

**Comment by evgzor** [comment]
the same problem -- macOS Sierra, shell we manually compile?

**Comment by LeonidKokhnovich** [comment]
When I try to build it, it says SourceKittenFramework is missed. Also signing identities are set to the personal apple dev profile.

**Comment by seanhenry** [comment]
The dependencies require manual building at the moment.

Sorry for the bad upload. I downloaded it and unzipped it and it was the same.

I've replaced it with another binary on the same release page. I've downloaded it and I can install it now (once gatekeeper is happy). Let me know if this fixes the problem.

**Comment by LeonidKokhnovich** [comment]
Thanks, it works!

**Comment by seanhenry** [comment]
🎉
