### ISSUE TITLE
New Swift parser ignores inheritance

### ISSUE THREAD

**Issue by MercyBeat** [seanhenry/SwiftMockGeneratorForXcode#12]
It seems like the parser change in release v1-beta.11 does not catch inherited members from parent protocols. It should traverse the inherited members.

**Comment by seanhenry** [comment]
Hi. Thanks for raising this issue. I’m working on a feature to support inherited protocol members and also multiple inherited protocols. I’ll post any updates here.

**Comment by seanhenry** [comment]
I've uploaded a release which supports mocks conforming to more than 1 protocol. See [here](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases/tag/v1-beta.13) for details.
