### ISSUE TITLE
Impossible to install and/or use the app if Xcode is renamed

### ISSUE THREAD

**Issue by CyberDandy** [seanhenry/SwiftMockGeneratorForXcode#15]
Having multiple versions of Xcode on my Mac, I have them named different ways (Xcode_9_4_1.app, Xcode_10.app, ...). When I open the app to install it in that configuration (with no app called Xcode.app), as soon as I select setup popup, a "Choose Application" popup appears in loop, the app being unresponsive, and me being unable to install it. I tested it on the last two releases with the same result.

When I rename one of my Xcode apps back to Xcode.app, then it works normally - the "Choose Application" popup doesn't appear as Xcode.app is automatically detected, without me having the possibility to select a different Xcode application, by the way.

This bug prevents users to install SwiftMockGeneratorForXcode on multiple version of Xcode, to install it on renamed versions of Xcode, and simply to choose on which Xcode application to install it - all of which should definitely be possible to do.

Thanks in advance for looking into it whenever you have the time, I'll work around that in the meantime by renaming my Xcode applications as needed.

Note: changing the name to Xcode.app, installing SwiftMockGeneratorForXcode then renaming it to Xcode_xxx.app doesn't solve the problem, trying to generate a mock then would trigger an error - ```Couldn't communicate with a helper application```.

**Comment by seanhenry** [comment]
Hi @CyberDandy 

Thanks for raising this issue. I think I know what the problem might be. I'll look into it now.

**Comment by seanhenry** [comment]
Hi @CyberDandy 

This issue is now fixed in the [latest release](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases/tag/v1-beta.17) 🎉

If you still have a problem, please feel free to reopen this issue.
