### ISSUE TITLE
Mock Generator did not show in the Extensions menu until I renamed the app

### ISSUE THREAD

**Issue by j531** [seanhenry/SwiftMockGeneratorForXcode#17]
As per the title. I couldn't get the app to show in System Preferences until I renamed the application (I removed 'For Xcode' from the end).

Using OS X 10.13.6 and Mock Generator v1-beta.16.

Cheers

**Comment by seanhenry** [comment]
Hi @j531 

Thanks for raising this issue. I am able to see the app in System Preferences with the full name so I'm not sure why you couldn't. It might be worth me shortening the name of the app bundle anyway!

**Comment by seanhenry** [comment]
@j531 could you delete your renamed copy of the app and install the [new release](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases/tag/v1-beta.17)? You should be able to see it in the Extensions window without having to rename the app. Let me know if not :)

**Comment by j531** [comment]
Yeah, it works without renaming this time, thanks.
