### ISSUE TITLE
Subscript support.

### ISSUE THREAD

**Issue by BohdanOrlov** [seanhenry/SwiftMockGeneratorForXcode#18]
Hey, @seanhenry!
I've realised that subscript is not supported: 

![image](https://user-images.githubusercontent.com/6740223/47659935-e560d400-db8d-11e8-9679-22ce8c21b8eb.png)

```
protocol FeatureFlagsByKeyStoring: class {
    subscript(key: String) -> Bool? { get set }
}

class MockSubscript: FeatureFlagsByKeyStoring {
    
}
```
is is a known issue or something you want to support in future?

**Comment by seanhenry** [comment]
Hey @BohdanOrlov 

Thanks for raising this issue. I haven’t added support for subscripts yet. I’ll add support for them soon.

**Comment by seanhenry** [comment]
Hey @BohdanOrlov 

Generating test doubles from subscripts is [now available](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases/tag/v1-beta.19) 🎉
