### ISSUE TITLE
Xcode doesn't show Mock generator in Edit tab

### ISSUE THREAD

**Issue by LeonidKokhnovich** [seanhenry/SwiftMockGeneratorForXcode#2]
After following this steps:

Download the latest release here
Copy the app to the Applications folder.
Open the app
Select the path to your project (Why do I have to do this?)
Open Xcode

I don't see any mock specific subtab in the editor tab.
Xcode Version 8.3.2 (8E2002)
Swift Toolchain: Swift 3.0.1

**Comment by LeonidKokhnovich** [comment]
I wonder if I need to install Xcode extension separately...

**Comment by seanhenry** [comment]
Opening the MockGeneratorApp should automatically install the extension. Perhaps try restarting Xcode?

Otherwise try opening System Preferences -> Extensions and see if the extension is listed in the Xcode section?

**Comment by LeonidKokhnovich** [comment]
It looks like it's disabled by default in Preferences -> Extensions. If I enable it manually, it works!

**Comment by seanhenry** [comment]
Great. Did you manage to generate a mock?

I'm not sure whether it is disabled by default or whether it happened because of the bad app you downloaded earlier but I'll add it as an installation step in the readme. 

Thanks for reporting this!

**Comment by LeonidKokhnovich** [comment]
Yes, I was able to generate a mock. Thanks!
