### ISSUE TITLE
Can't build a project

### ISSUE THREAD

**Issue by vlondon** [seanhenry/SwiftMockGeneratorForXcode#27]
Hello!

I'm trying to build a project but it requires `SwiftToolkit` and it's trying to clone it from `git clone git@bitbucket.org:seanhenry/swift-toolkit.git` but failing with `Please make sure you have the correct access rights and the repository exists.`

**Comment by LuLuElayne** [comment]
I don’t know what 2do.

**Comment by seanhenry** [comment]
Hi,

Thanks for raising this issue. I have a little note about this in the README; this project currently relies on some private libraries so it can't be compiled publicly at the moment.

I am actively working on changing this but it is a big change so won't be ready any time soon. 

Let's keep this issue open and I will comment here when there are any updates.

**Comment by jbfitb** [comment]
What do the private libraries do?

**Comment by seanhenry** [comment]
An extension like this needs to be able to inspect the structure of a Swift file to understand how to implement a protocol or subclass a class. Xcode extensions get the file contents but not much else information to work with and SourceKit provides some of this information but it’s far too basic to use on its own. So the private libraries are there to parse, resolve and format the Swift code to make powerful extensions.

**Comment by jbfitb** [comment]
Ae all the private libraries from Xcode extensions? If this is open source, why can't the libraries be too?

**Comment by seanhenry** [comment]
The private libraries are being used in another project and are unfortunately not open source. 

Can you tell me what you’d like to do with the project?

**Comment by jbfitb** [comment]
Our security team won't let us use a library they can't inspect. The worry is all our code could be stolen through these private libraries that are not open source.

**Comment by seanhenry** [comment]
I see, I can’t do much about sharing the code but feel free to put them in touch with me if that helps.

**Comment by seanhenry** [comment]
As of v0.25, this project can be downloaded and run by everyone

**Comment by jbfitb** [comment]
Awesome @seanhenry. What changed?

**Comment by seanhenry** [comment]
The compiled external libraries have been added to source control. Checkout the `master` branch to try building.
