### ISSUE TITLE
Cannot set up Swift Mock Generator for Xcode in System Preferences

### ISSUE THREAD

**Issue by bertrandprenat** [seanhenry/SwiftMockGeneratorForXcode#30]
Hello,

I am having issues setting up `Swift Mock Generator for Xcode` in `System Preferences`: when I go to `Security & Privacy` > `Privacy` > `Automation`, the app is not listed.

I have tried to reinstall the app, nothing changed.

Can you take a look at this issue?

Thank you!

**`macOS` version: macOS Mojave (10.14.6)
`Xcode` versions: 10.3 and 11.1
`Swift Mock Generator for Xcode` version: 0.23**

**Comment by seanhenry** [comment]
Hi @bertrandprenat 

Thanks for raising this issue. 

Could you help me figure this out by answering these questions:
- Is 0.23 the first version of this app you have tried? Or is this an upgrade problem?
- Have you ever received a prompt to allow the app to control Xcode?
- Do you see the app in `System Prefs -> Extensions -> Xcode Source Editor`?
- Can you see the Mock Generator option in Xcode's `Editor` tab? (Make sure a Swift file is open in the editor)

**Comment by fmirault** [comment]
Same problem for me for no reason, I haven't changed anything but suddenly it stopped working.

- 0.23 is the version that worked perfectly
- I already received a prompt to allow the app to control Xcode, in fact eveything is checked (even if I got an alert telling me "Mock Generator does not have permission to access Xcode.
Go to System Preferences -> Security & Privacy -> Privacy -> Automation and make sure this app is allowed to control Xcode."
- The app is listed in System Prefs -> Extensions -> Xcode Source Editor
- I can see Mock Generator option in Xcode's Editor tab, but greyed

**Comment by seanhenry** [comment]
Hi @fmirault 

Just to clarify, what do you mean by:
> 0.23 is the version that worked perfectly

Do you mean it did work but is not working now? Or did upgrading to 0.23 fix the problem?

Are you running Mojave too?

**Comment by fmirault** [comment]
Hi @seanhenry 

I'm running Mojave, and 0.23 worked well (you know about the slow processing to generate stubs that was corrected in this version), but this morning I have this alert.

I really don't know how to help you more :(

**Comment by seanhenry** [comment]
Try [this update](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases/tag/v1-beta.24). I think there was a Capabilities problem. 

Does that fix your issues?

**Comment by fmirault** [comment]
Everything works as expected now 🎉 ! Thank you so much for such quick fix ;)

**Comment by bertrandprenat** [comment]
Good morning @seanhenry!

Thank for your quick response!

To answer your questions:

- Is 0.23 the first version of this app you have tried? Or is this an upgrade problem?
  - It is the first version I have tried.
- Have you ever received a prompt to allow the app to control Xcode?
  - Yes I have.
- Do you see the app in System Prefs -> Extensions -> Xcode Source Editor?
  - Yes.
- Can you see the Mock Generator option in Xcode's Editor tab? (Make sure a Swift file is open in the editor)
  - Yes, the option is available in Xcode, but I get an error message (_"Could not detect your project. Enter one in the companion app."_).

**Comment by bertrandprenat** [comment]
It's working now!!! 🤘🏻

**Comment by seanhenry** [comment]
Great! Thanks to both of you for helping me fix this :)

**Comment by Raghavendra-Shedole** [comment]
@seanhenry Hi, I am looking for similar kind of extension but bit different naming format and what do i need to do for that? is it possible to change the mustache a bit to achieve it.
