### ISSUE TITLE
Cannot set up Swift Mock Generator for Xcode in System Preferences extensions

### ISSUE THREAD

**Issue by fmirault** [seanhenry/SwiftMockGeneratorForXcode#32]
Hello,

I am having issues setting up Swift Mock Generator for Xcode in System Preferences: when I go to System Preferences -> Extensions -> Xcode Source Editor,  the app is not listed.
Because of this, when I go to Editor, there is no 'Mock Generator' entry.

However, if I go to Security & Privacy > Privacy > Automation, the app is listed and checked.

I have tried to reinstall the app, nothing changed.

Everything worked well until this new year, maybe there is something about capabilities / signing ?

Thank you!

macOS version: macOS Catalina (10.15.1)
Xcode versions: 11.3
Swift Mock Generator for Xcode version: v1-beta.24

**Comment by seanhenry** [comment]
Hi @fmirault 

The certificates look ok to me. Try the following command in terminal:

```
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Xcode.app
```

**Comment by fmirault** [comment]
Worked perfectly! Thank you!
