### ISSUE TITLE
[Feature request] Support from command line

### ISSUE THREAD

**Issue by federico-jordan-peya** [seanhenry/SwiftMockGeneratorForXcode#34]
Hi guys, awesome work!
Do you know how can I run the mock generator from terminal? I'd like to automate some process and the tool is perfect to do my mocks.
Thanks in advance!

**Comment by seanhenry** [comment]
Hi @federico-jordan-peya 

Thanks for raising this issue. I'm pleased you like the extension.

There isn't currently a command line tool but one could be added quite easily. What would you need it to do? Scan a directory and generate all mocks matching a certain pattern?

**Comment by federico-jordan-peya** [comment]
Yes, I think that would be great! 
Also it can be added as a precommit hook, or maybe as a test target build step.

**Comment by seanhenry** [comment]
Great, I'll look into it. 

You might want to see what the performance is like before using a build step or commit hook but it should be fine for a small number of mocks.

**Comment by federico-jordan-peya** [comment]
Yes, I'm also aware of that. I think that the main benefit would be just running it from command line to update many mocks at once. 
Thanks you very much

**Comment by federico-jordan-peya** [comment]
Maybe we can filter the mocks with some comment on top of the class name like `/// @GenerateMock`

**Comment by seanhenry** [comment]
Hi @federico-jordan-peya 

I've added a command line tool in the [latest release](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases). Let me know what you think.

**Comment by federico-jordan-peya** [comment]
Excellent @seanhenry, I will test it on my project. Thank you very much for attending the feature
