### ISSUE TITLE
Mojave and Xcode 11.3 Support

### ISSUE THREAD

**Issue by agprateek16** [seanhenry/SwiftMockGeneratorForXcode#36]
Hi, 
The current version is not compatible with Xcode 11.3 and Mojave. Can you please direct me to a version which supports this configuration.

**Comment by seanhenry** [comment]
Hello @agprateek16 

Thanks for raising the issue. There aren't any builds compatible with Xcode 11.3 and Mojave. The only Mojave compatible builds work with Xcode 10.

If you can't update to Catalina, I will try to make a build for you if you are happy to test that it works and feed it back to me so I can make a release. Are you happy to do that?

**Comment by agprateek16** [comment]
Yes. I am more than willing to trying out the build.

**Comment by seanhenry** [comment]
Great! You can download the build [here](https://www.dropbox.com/s/pu8un5yrhhrg09l/Swift%20Mock%20Generator%20for%20Xcode.dmg?dl=0).

If it works for you then I will publish an official release. Thanks for your help!
