### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by davidthorn** [seanhenry/SwiftMockGeneratorForXcode#38]
Looks like a great tool.
I was hoping to use this tool 'out of the box', but the initial documentation is confusing about how to actually install it:

Install Swift Mock Generator Xcode Source Editor Extension:
Close Xcode if it is open:  (check)

Download the latest release here (check)

Copy the app to the Applications folder. (What app?)

Open the app (What app?)

.. Gave up

**Comment by hendych** [comment]
<img width="981" alt="Screen Shot 2020-08-10 at 18 09 38" src="https://user-images.githubusercontent.com/8999432/89776808-cd74fd00-db34-11ea-9ed6-b9f38a50b27c.png">
- Open **Releases**, and then select release version you want to install.
- Expand the **Assets** and you will see the dmg file
