### ISSUE TITLE
ObjectToTest ？？？？

### ISSUE THREAD

**Issue by tomlee130** [seanhenry/SwiftMockGeneratorForXcode#44]
What's this -> ObjectToTest
where is ObjectToTest's implementation

**Comment by seanhenry** [comment]
Hi @tomlee130 

In the readme example `ObjectToTest` would be the type that you would like to test. I haven't written the implementation but in this example it would look something like this:

```
class ObjectToTest {
  
  private let animator: Animator

  init(animator: Animator) {
    self.animator = animator
  }

  func myMethod() {
    animator.animate(duration: 1, animations: { }, completion: { })
  }
}
```

**Comment by tomlee130** [comment]
> Hi @tomlee130
> 
> In the readme example `ObjectToTest` would be the type that you would like to test. I haven't written the implementation but in this example it would look something like this:
> 
> ```
> class ObjectToTest {
>   
>   private let animator: Animator
> 
>   init(animator: Animator) {
>     self.animator = animator
>   }
> 
>   func myMethod() {
>     animator.animate(duration: 1, animations: { }, completion: { })
>   }
> }
> ```

That 's Good ,Tks
