### ISSUE TITLE
Use apple script to get current Xcode project directory

### ISSUE THREAD

**Issue by LeonidKokhnovich** [seanhenry/SwiftMockGeneratorForXcode#7]
I wonder if it was considered to use Apple Script (https://gist.github.com/schwa/3822611) to check what is the currently opened project folder instead of manually specifying it in the mock generator util.

**Comment by seanhenry** [comment]
Interesting. I haven’t considered using AppleScript for something like this. 

I’d be interested to know how you’re using the mock generator. Do you tend to have multiple projects open at the same time? Or are you changing projects frequently?

**Comment by LeonidKokhnovich** [comment]
I have an app project that includes few other subprojects. 
Subprojects are _not_ stored within the main app directory.
I usually switch between them quite often while working on the main app. 
In order to make the mock generator work, I have to specify the root folder for all Xcode projects and that's why mock generator sometimes works quite slowly for me (10+ seconds).

**Comment by seanhenry** [comment]
I can see why that’s annoying. Let me look into this.

**Comment by seanhenry** [comment]
I've created a [release](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases) to detect the directory of the open Xcode project. It should fix your problem as long as you are opening your subprojects in another Xcode window and not editing them directly from your main project. 

It would be useful to get your feedback when you've tried it out.

**Comment by LeonidKokhnovich** [comment]
It works, thank you!
