### ISSUE TITLE
Generates mock conforming to multiple protocols

### ISSUE THREAD

**Issue by LeonidKokhnovich** [seanhenry/SwiftMockGeneratorForXcode#9]
Hey! Thanks for a great support of this extension! I wonder how difficult to migrate support for generating mock for multiple protocols from AppCode extension? In the readme, I assume it's called "Generates mock conforming to both classes and protocols."

I'm talking about this use case:
```
protocol SelectableType { 
  func select()
}
protocol ReadableType { 
  func read()
}
protocol TextFieldType: SelectableType, ReadableType {
  func display()
}

class TextFieldMock: TextFieldType {
  func select() {
    ..
  }

  func read() {
    ..
  }

  func display() {
    ..
  }
}
```

**Comment by seanhenry** [comment]
Hi! This would be a nice feature to move into the Xcode plugin. It’s tied into the AppCode implementation at the moment so I’ll look at extracting it to make it reusable as soon as I can. Watch this space :)

**Comment by rckim77** [comment]
I'd also like to see this as a feature! Are there any workarounds for the time being?

**Comment by LeonidKokhnovich** [comment]
@rckim77 On my side as a workaround, I declared a separate mock class that confirmed to 1 of the protocols, generated code through the mock generator, inserted into the base mock class and repeated for each of the protocols that the mock should confirm to.

**Comment by seanhenry** [comment]
That sounds like the only work around for now unfortunately. I’m working on this feature but I’ve been slowed down by some other projects. I’m aiming to get support out for this soon. Thanks for your patience!

**Comment by seanhenry** [comment]
I've (finally) uploaded a [release](https://github.com/seanhenry/SwiftMockGeneratorForXcode/releases/tag/v1-beta.13) to support multiple protocols. Thanks for your patience on this one!
